<?php
 return [
  'name' => 'events',
  'label' => 'Events',
  'info' => 'Termine und Veranstaltungen',
  'type' => 'collection',
  'fields' => [
    0 => [
      'name' => 'title',
      'type' => 'text',
      'label' => 'Titel',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => true,
      'multiple' => false,
      'meta' => [],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
      ],
    ],
    1 => [
      'name' => 'start',
      'type' => 'datetime',
      'label' => 'Startdatum',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
    2 => [
      'name' => 'end',
      'type' => 'datetime',
      'label' => 'Enddatum',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
    3 => [
      'name' => 'description',
      'type' => 'textarea',
      'label' => 'Beschreibung',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
    4 => [
      'name' => 'image',
      'type' => 'asset',
      'label' => 'Bild',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
  ],
  'preview' => [],
  'group' => '',
  'meta' => NULL,
  '_created' => 1763400000,
  '_modified' => 1763400000,
  'color' => NULL,
  'revisions' => false,
];
