<?php
 return [
  'name' => 'news',
  'label' => 'News',
  'info' => 'Neuigkeiten und Blog-Beitraege',
  'type' => 'collection',
  'fields' => [
    0 => [
      'name' => 'title',
      'type' => 'text',
      'label' => 'Titel',
      'info' => '',
      'group' => '',
      'i18n' => false,
      'required' => true,
      'multiple' => false,
      'meta' => [],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
      ],
    ],
    1 => [
      'name' => 'teaser',
      'type' => 'text',
      'label' => 'Teaser',
      'info' => 'Kurze Vorschau fuer die Uebersicht',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [
        'multiline' => true,
        'showCount' => true,
        'maxlength' => 200,
      ],
    ],
    2 => [
      'name' => 'content',
      'type' => 'wysiwyg',
      'label' => 'Inhalt',
      'info' => 'Der vollstaendige Artikel-Text',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
    3 => [
      'name' => 'image',
      'type' => 'asset',
      'label' => 'Bild',
      'info' => 'Titelbild fuer den Artikel',
      'group' => '',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [],
      'opts' => [],
    ],
  ],
  'preview' => [],
  'group' => '',
  'meta' => NULL,
  '_created' => 1763398187,
  '_modified' => 1763400000,
  'color' => NULL,
  'revisions' => false,
];
