spring.application.name=infopoint
server.port=8888

# Cockpit CMS Konfiguration
cockpit.url=${COCKPIT_URL:http://localhost:8080}
cockpit.api-key=${COCKPIT_API_KEY:API-c603802aed1873dbb9ad600f771780aff83a085e}
